### ISSUE TITLE
CreateServer should fail and specify the reason when the flavor is wrong

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#1043]
Refs #956, #1041.

**Comment by cyli** [comment]
Wondering if this can be combined with https://github.com/rackerlabs/otter/issues/1043 for "Nova has returned 400" - not sure we should enumerate every single possible 400 error Nova can give us, especially since we don't validate most of the nova blob.

For instance, the key name might be wrong, nova metadata might be in the wrong format, etc.
