### ISSUE TITLE
AddNodesToCLB should fail on 25 nodes limit

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#1214]
It should return `StepResult.FAILURE` when 25 nodes limit error occurs since group cannot scale anymore after that. Can be done after #1189.

**Comment by cyli** [comment]
It seems like there might be some race conditions (which we might be fine with) on the 25th node..

Let's say the user scales up by one, and then deletes another server out of band.  We can add the server to the load balancer in a bit, after we've cleaned up the deleted server, but if the good server becomes active first and we try to add it to the load balancer, this would put their group into a failure state, whereas if we waited a minute or two it would have been fine.

This might be ok though, since the user probably shouldn't count on quick things like that - just wondering if we are ok with this being a case where the group goes into failure and needs user intervention to get started again.

**Comment by manishtomar** [comment]
I think its ok for the group to goto ERROR on user intervention. It's probably not ok to be in ERROR due to our internal implementation, i.e. if the user only uses AS API to scale up/down and group goes to ERROR due to race condition it will be unacceptable.

**Comment by cyli** [comment]
Ok.  Is there any other case where we might have both AddNodesToCLB and RemoveNodesFromCLB going at the same time, that might cause a race condition with the number of nodes?
