### ISSUE TITLE
Efficiently throttle server creation in convergence

### ISSUE THREAD

**Issue by radix** [rackerlabs/otter#1225]
We need to maintain parity with the existing worker code and make sure to not run multiple CreateServer requests at the same time.

However, the basic convergence throttling isn't really great at this, because if we throttle it to one CreateServer at a time, it'll cause N convergence iterations where N is the number of servers to create, and that's super inefficient.

So we should have an optimizer for CreateServer steps that aggregate them into a CreateServers step, which does its own throttling.

**Comment by cyli** [comment]
We should also make the limit configurable, since this greatly speeds up the otter/integration (as opposed to the cloudcafe integration, although it might help those too) tests.

**Comment by radix** [comment]
well apparently they only ask for 1s between creation requests so it may not matter, but yeah we could configure it to 0 for our mimic integration tests.

**Comment by manishtomar** [comment]
I've never been comfortable with planner doing throttling. Throttling is pure execution strategy and should exist in executor which in our case is `execute_convergence` function. There can be `execute_steps` instead of `steps_to_effect` that takes the steps and executes them using some throttling policy. This method can return `worst_status` depending on how much it managed to execute.

**Comment by radix** [comment]
@manishtomar the "planner doing throttling" is a vague concept, and I don't think a very accurate characterization of what I suggested. My proposal is to have a function of steps -> steps, which can be easily composed into the flow of steps to be executed, and doesn't need to affect either the way steps are originally produced (with `converge`) or performed (with `execute_convergence`). The core logic of `converge` remains as clean as it is today, and we only have to write another function and compose it into `plan`. So yes, I do propose `plan` invoke the work of throttling our steps, but `plan` is only a trivial composition of other things (plan, optimize, throttle), and it will remain so.

Maybe I'm missing something and there's some good reason to put this logic into `execute_convergence`, but right now it seems keeping it separated is beneficial.

Keeping all of this stuff in step-world maintains a nice "functional core, imperative shell" where our internal plan can transparently represent the logic of a convergence iteration without involving opaque things like Effects. This means that more of the logic is easily testable without invoking Effect-y stuff in our tests.

Also, if you're concerned about having throttling be specific to CreateServer, we can easily generalize this concept of throttling steps within a convergence iteration by having a generic step that can throttle any set of other steps, and I recommend we do that (I think we've already got a request from the nova to also throttle deletions, so it will be immediately useful).

**Comment by cyli** [comment]
Isn't our existing throttling already generalized?  It throttles based on step type.

**Comment by radix** [comment]
@cyli The problem is that, if we only want one server creation HTTP request to happen at a time, the current mechanism would only allow that by only allowing 1 CreateServer step per convergence iteration. That's really heavy-weight because 1) we only need a delay of ~1s, and 2) each convergence iteration is super heavy and we don't really need a whole gathering process for every single create server call.

So the proposal here is to have a `RateLimitStep` (or something) which takes a list of substeps and runs them in sequence with a short delay between each. It will run them all within one convergence cycle.

**Comment by cyli** [comment]
@radix ah, yes, agree, that would speed things up a lot.  thanks for explaining

**Comment by manishtomar** [comment]
@radix I completely agree with advantages of having as much functional core as possible. I just feel throttling should not be concern of planner (`plan.py`). It can be in (say) `executor.py` that does as much as possible functionally (steps -> steps function(s)) and the rest with effects. Basically let the plan have only `converge` and `optimizer` and move throttling steps transformation functions to `executor.py. Let me know if this helps in clarifying what I indented to say.

**Comment by radix** [comment]
@manishtomar I don't really understand why a function of  `steps -> steps` should be in the same module as the code with the effects. steps are currently the domain of `planning.py` and `steps.py`. But I'm not as concerned about module layout, mostly just the dataflow of the code, so no big deal to me.

**Comment by radix** [comment]
@manishtomar actually I do like the idea of a new module. It should have all the step->step translators, like the current throttling code, and the current optimization code, and also the new throttling function described in this ticket. I still don't like the idea of having the Effect code in the same place, though, so I'd recommend some other name than `executor.py` -- perhaps `optimizing.py`, `compiling.py`, or `translating.py`. I think there was actually a suggestion for this module way back when we originally discussed the `otter.convergence` reorganization with glyph...

**Comment by cyli** [comment]
@manishtomar Are you suggesting it happen in execution because the throttling has to be global (e.g. across all groups for all tenants on a node)?  It seems like @radix's suggestion for steps->steps works pretty well for throttling creations within a group itself, but maybe if Nova wants us to send them no more than 1 create request at all per second...

**Comment by manishtomar** [comment]
> Are you suggesting it happen in execution because the throttling has to be global (e.g. across all groups for all tenants on a node)?

@cyli My original idea is to separate code based on its function rather than its type but yeah unfortunately we need to throttle based on a global level before releasing it for customers. I always imagined `executor` to be this black box were all steps are sent and it will execute them in some order with some throttling but that maybe difficult since we need the result of step executions. It _might_ be possible to ignore step results if converger strictly depends on observer but we don't need to worry about that now :).

**Comment by cyli** [comment]
@manishtomar Hmm... wondering if we should build rate limiting into our cloud client instead?  Rather than have the executor then have to extract particular steps and limit them from the bag of steps to execute.

So if we call create_server, for example, our client can specifically rate limit that call exactly.  We can build rate limiters into all the cloud client function calls maybe...

This doesn't necessarily ensure equitable distribution of calls though between tenants/groups :|  So maybe it has to happen in both places?

**Comment by radix** [comment]
Oh, this is already fixed by #1412.
