### ISSUE TITLE
Can't use otter `delete server` REST API on servers that were created with convergence

### ISSUE THREAD

**Issue by radix** [rackerlabs/otter#1238]
The `active` data stored in cassandra for convergence-created servers doesn't have all the data that is usually there, and the deletion code depends on this. Here's the exception I'm getting:

```
Traceback (most recent call last):
  File "/opt/otter/otter/supervisor.py", line 384, in start
  self.log, self.trans_id, self.scaling_group, self.server_info)
  File "/opt/otter/otter/supervisor.py", line 196, in execute_delete_server
    return d.addCallback(got_request_bag)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 307, in addCallback
    callbackKeywords=kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 296, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/opt/otter/otter/supervisor.py", line 192, in got_request_bag
    instance_details = server['id'], server['lb_info']
exceptions.KeyError: 'lb_info'
```

**Comment by manishtomar** [comment]
The `delete_server` implementation needs to change: When deleting out of group not from Nova, otter should remove group metadata. Otherwise, it should just delete the server and update it's active list.

**Comment by radix** [comment]
@manishtomar what do you mean "not from Nova"?

**Comment by manishtomar** [comment]
@radix I meant remove from the group but do not delete the server. In our case it is `DELETE .../groupId/servers/serverId?purge=false`

**Comment by radix** [comment]
@manishtomar the problem is that LB information is not available, and otter wants to remove the server from the load balancer.

**Comment by manishtomar** [comment]
Since otter was the one that added to the LB, I think its fine that otter removes it from LB. In convergence it can get that from metadata.

**Comment by radix** [comment]
@manishtomar ah, so you're saying when deleting a server, otter should hit nova directly to determine what load balancer it's associated with it, instead of relying on the cached data in `active`?

**Comment by manishtomar** [comment]
Actually, I had not thought of that but it does sound like a good plan. I was thinking about extracting LB information from server metadata.

**Comment by radix** [comment]
@manishtomar not even the metadata is stored in `active` for convergence-created servers -- the whole problem is that creating servers through convergence is basically not storing any data about the server other than the ID. see https://github.com/rackerlabs/otter/blob/master/otter/convergence/service.py#L37

**Comment by cyli** [comment]
I'm thinking that when it stores active servers, it extracts the desired LB info from the metadata and sticks it in the dict?

**Comment by manishtomar** [comment]
@cyli Yes it should extract LB from metadata and update the cache. Sorry @radix and I discussed on Slack and did not conclude it. The idea is `active` list should always be treated as read-only cache

**Comment by cyli** [comment]
Sorry to be clear, should I be putting `lb_info` in the cache, so that `delete_server` can use it to delete the server?  This means the code path for `delete_server`, even for convergence tenants, go through the worker.

We could possibly just check to see if the server is a member of the autoscale group (check Nova to do so), and if so, set the metadata item "DRAINING" on it.  Then kick off a convergence cycle.  Convergence will figure out what load balancer magic has to be done on it then.

**Comment by radix** [comment]
@cyli of course we talked about this on slack, but I'll answer here for posterity:

don't add anything to the `active` list (if that's what you mean by "the cache") -- we'll just have the code for deleting servers fetch the data from nova directly in order to find the LB info in its metadata. Your idea about using setting a server to `DRAINING` if it has LB info is good. And, as you said on slack, if no LB info is found on the server, just delete it immediately.

**Comment by cyli** [comment]
Looking at the code some more, it looks like the simplest thing we can do to just make this work for now is to replace the part of `supervisor.remove_server_from_group` that delete the server and replace the server with just a call to set the server metadata to indicate that it is draining.

The worker code will take care of the case where the server is evicted from the group (by scrubbing autoscale metadata from the server).

However, there are 2 caveats:
1.  We probably want to just make this a pass-through series of requests to Nova.  So if fails to set the metadata, maybe with some number of retries, the request to delete fails.
2.  We probably want to replace the worker code with effecting code at least, possibly with steps?  Since at some point, we probably want to eliminate most of the bare treq calls.

So given that, the questions are:

1.  Should calling this create and execute some steps, or just call some functions from `cloud_client`?
2.  Should we be replacing any of the worker code with effecting code for this?  Since they'll be doing almost the same thing?

**Comment by cyli** [comment]
At any rate, some steps I probably need to do before this is:
- [ ] Ensure that a draining server with no load balancers can be deleted right away
- [ ] Add a `cloud_client.py` function for setting metadata on a server/deleting metadata on a server, and parse any errors
- [ ] Add a `cloud_client.py` function for getting one server's details, and parse any errors

**Comment by radix** [comment]
1. I think it should just call some functions from cloud_client, potentially factored out from the current step implementations.
2. It doesn't _seem_ like using steps from the worker code here is the right way to go about it, so I think I'd rather just see some cloud_client functions being used. Do you want to share more code than just the stuff that would be in `cloud_client.py` with convergence? What would that shared code look like?

**Comment by cyli** [comment]
@radix:
> Do you want to share more code than just the stuff that would be in cloud_client.py with convergence? What would that shared code look like?

I just mean something should we have something like `convergence.?.delete_server`, and `convergence.?.evict_server`, which the supervisor code can switch between if it's a convergence client?

Or we can just call `cloud_client` that code inside of `supervisor.remove_server_from_group`.

`supervisor.remove_server_from_group` calls some worker code that makes some treq requests to remove metadata though - do we want to replace it to use just the effecting code?  Or do we want to make two full code paths, and have it switch between them?  Or do we want to just let the worker code with the bare treq requests handle evicting the server (removing metadata), and come back to replacing it later on when we start ripping out worker code?
