### ISSUE TITLE
CATC2: Basic scale down

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1311]
Convergence Automated Test Case 2

Scale Down: Given the number of permutations of this test, this will use generative testing to exercise various scaling factors, min/max constraints, policy types, and load balancers
- Create a scaling group with various launch configuration data
- Scale down by X servers
- Validate end group state

This test case represents a template for a set of generative tests. Select one case to automate as a representative sample.

This is not convergence specific, and the scenario is already tested in the Cafe tests.

**Comment by sam-falvo** [comment]
What needs parameterization specifically?  I have this case covered in the existing body of Trial tests, though it is a bit static.

**Comment by kivattik** [comment]
In the generative framework, I would like to see the following parameterized:
- group MIN
- group MAX
- cooldowns
- type of scale down (percent/scale to/scale by)
- Scaling factor (i.e. x%, scale to x, down by x) as relevant for selected type
- CLB present (0/1/2)
- Number of scale down operations

Note: Mathematically (and within the test case generator) this is just a subcase of the general case involving multiple policy executions. This was separated out to clarify mapping to existing static tests.

**Comment by kivattik** [comment]
Regarding existing tests: The 'qe: cafe overlap' tag was included to indicate that static tests already exist, although I wasn't aware they were in Trial. I'm open to alternate tag names that are more informative.

I think the action on this issue for now might just be to link to the existing test cases in this issue and in the test case document.

**Comment by sam-falvo** [comment]
I guess what I'm asking is, if the generative tester is responsible for running scenarios on its own, do I need to invest effort to parameterize the Trial tests?  It seems like I shouldn't, since the Trial tests are proper subsets of what the generative tester is capable of.

Basically I want to mark #1310 and its relatives done, since we already have static tests written for them.  They may not fuzz, but they at least exercise the control flows desired in Otter.  Thoughts?  (We only have 1.5 weeks left til end of month, so I'm looking to push out as many tests as I can in that time.)
