### ISSUE TITLE
CATC7: Scale over max after OOB deletion

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1316]
Scale over max after OOB deletion
	- Create a scaling group
	- Scale to MAX servers
	- Delete ‘z’ servers OOB
	- Attempt to scale up (i.e. beyond max)

**Comment by sam-falvo** [comment]
What is the expected result?

**Comment by kivattik** [comment]
This requires confirmation, but in the past an execution would fail with a 403 if the group already had max entities. In this case, I suspect that the policy would fail, but I'm not sure if it would trigger convergence to replace the servers up to max.

**Comment by manishtomar** [comment]
This is very good test case. Thanks for coming up with such scenarios :). This will force us to clarify our behavior. 

With convergence, this will fail with 403 and deleted servers will not be replaced since convergence will not be triggered. When convergence gets triggered in future for any reason (policy execution/`converge` API), the deleted servers will be replaced.

**Comment by kivattik** [comment]
#1344 

Expected behavior: Get 403, trigger convergence to replace deleted servers up to max
