### ISSUE TITLE
CATC10: Server Timeout on build

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1319]
Server Timeout on build
	- Validate that the expected group state is reached when servers timeout building
		- (ex. use mimic to Timeout 1/5 servers)

Prereq: Need to be able to configure Mimic to transition a subset of servers to build (building indefinitely)

**Comment by sam-falvo** [comment]
How is this different from #1318?

**Comment by kivattik** [comment]
The resultant behavior is similar, but in this case Otter decides that a server is timed out and will not complete, whereas in #1318 Nova indicates that an error occurred and Otter responds to the Nova state change.

**Comment by kivattik** [comment]
It does not look like this test is feasible at this time. While we could likely fast-forward mimic, this test requires that Otter fast-forward in order to recognize a timeout in less than 1 hour, and Otter does not support speeding up the clock.

**Comment by manishtomar** [comment]
For purposes of test, it should be possible to configure otter with reduced timeout. Created ticket #1368 for this.

**Comment by cyli** [comment]
@kivattik and I were discussing this IRL and wondering if we could backdate the mimic server build time, which would mean that otter would see it as being built for way too long on the next convergence cycle.

**Comment by manishtomar** [comment]
That seems fine. That would require mimic change and the test would be fast. I was thinking of having small build timeout (~ 30s) in otter and have server building for 1 min. This way mimic does not need to change but the tests would be longer. What would you prefer? I am fine either way.

**Comment by cyli** [comment]
@manishtomar at any rate as you said, a configurable timeout is a good idea anyway :D

**Comment by sam-falvo** [comment]
+1 on the configurable timeout.

@cyli Can you explain more what you mean by backdate in mimic?  I'm not sure I understand.  It doesn't seem like changing mimic will help test the edge case that this CATC is intending to exercise.

@kivattik After re-reading the thread on this ticket, I'm thinking we need mimic to keep a server in BUILD state, not in ERROR.  Otherwise, it's the same test as the one I linked to originally.

Am I misunderstanding?  Thanks.

**Comment by cyli** [comment]
@sam-falvo Autoscale looks at the creation time on the server to determine how long it's been building (otter's current time - the build time stated on the server).  If it's been building too long, otter kills it.

If we make the server remain in building forever, then the tests can go and change the server's creation time in order to make otter think it's been in building for too long, rather than telling otter to speed up time.

I don't believe this is currently supported in mimic, though.

**Comment by sam-falvo** [comment]
OK, that's an implementation detail I wasn't aware of.  That puts everything into context.  I'd like to try adding that to mimic; but would feel more comfortable if I paired with someone to minimize the time I spend trying.  That should be a fairly simple change to mimic, I think.

**Comment by cyli** [comment]
It's probably not great for the tests to rely on an implementation detail, and retconning server build time seems kind of sketchy to me, but it may be a shorter path to the same effect than setting up otter's clock.  Not sure - that may be entirely doable.

@manishtomar's suggestion is also a good one in that if we decrease the build timeout in otter for the tests to be about 60 seconds, we can just have the tests just wait that out.

**Comment by sam-falvo** [comment]
I agree that we should not depend on implementation details.  I'd rather wait until the adjustable timeout is implemented.  If we know the adjustable timeout can be implemented relatively soon, we can always defer this CATC until sometime in May.  However, end of May is the hard deadline.

**Comment by manishtomar** [comment]
Adjustable timeout in otter is a very small task. Can be done in a few days. Lets go ahead with that. I'll try to finish that by next week.
