### ISSUE TITLE
CATC26: Simulate identity errors by fail to authenticate client x% of the time 

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/otter#1334]
Simulate identity errors by fail to authenticate client x% of the time (NOTE: The case of constant Identity failures is not convergence related)
	- Set up Mimic to return identity error on auth attempts x% of the time
	- Create a group
	- Create multiple policies on the group
	- execute policies in sequence
	- Confirm that group eventually reaches desired state

Prereq: Mimic MUST be able to perform the specified behavior simulation
Prereq: This test case and behavior must be more clearly defined

**Comment by sam-falvo** [comment]
Is this a case where we need to create, say, 1000 policies, and execute all of them?  I ask because in order to guarantee that we actually run into 33% identity failures, we need to create at least 100 Identity API hits, and hope that chance bunches enough failures within that span to meet that ratio of failures.

Then there's the question of, are the failures bunched together over time, or evenly spaced?

(We can more or less guarantee that failure rate using a Digital Differential Analyzer inside of Mimic to produce evenly spaced failures.)

**Comment by kivattik** [comment]
I don't think we would need to create that many policies, since you hit auth on execution unless it is a webhook URL, but it would be one option. This tests would definitely need to be able to essentially fast-forward time, and even so, I might take a while. 

Ideally, the failures would be fairly random, but I think evenly spaced would be sufficient. 

I'd actually like a wider audience to weigh in on whether this is considered a mandatory test or if it should be classified as a robustness/performance test and implemented with performance testing at a later date. Thoughts?

**Comment by manishtomar** [comment]
I think this is a very useful test case to have since otter is specifically designed to handle random auth failures by getting new token on 401 and retrying. Initially I think its fine to have simple test case that just triggers a single 401 and expect convergence to still work. For example, execute a +1 policy where mimic fails with 401 once and works after that. 

Later, there can be performance tests where x% of auth failures are simulated.

**Comment by sam-falvo** [comment]
This seems much more reasonable, I think.  :)

**Comment by cyli** [comment]
To clarify - I'm interpreting this issue as us injecting errors into identity responses.  Like when otter authenticates/attempts to impersonate a user?  We do retry on those, no matter what the error.

When we make requests to Nova, we also re-authenticate if we get a 401.  In production, that is actually an identity issue, but in Mimic, that would be injecting errors into the response from Nova.  That seems like it'd be covered by issue #1332 (CATC-24)

**Comment by sam-falvo** [comment]
Yes, that is a reasonable interpretation.

**Comment by cyli** [comment]
Oops, forgot to close this.  Was fixed by #1492
