### ISSUE TITLE
Metrics script should email about divergent groups

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#1649]
Since metrics is continuously getting all the group's desired and actual, it can know if a group is diverged for a long time. If so, it can send out email listing those groups. This way we know proactively and can debug or inform customer/support.

Since running the dashboard, I've been trying to manually find divergent groups and fixing them (by converging) apart from debugging why they are divergent. With this email, I can avoid the extra step of finding the divergent groups.

This needs https://github.com/rackerlabs/autoscaling-chef/issues/762 completed.

**Comment by manishtomar** [comment]
@wirehead / @radix / @cyli Thoughts?

**Comment by cyli** [comment]
Just to clarify, is there a threshold for how long a group has been divergent before the email goes out?

**Comment by manishtomar** [comment]
> Just to clarify, is there a threshold for how long a group has been divergent before the email goes out?

@cyli Thats a good question. The same has been asked in #1287 but not yet answered. While thinking about this a little more I was thinking of emailing when the group has not _changed_ for too long, i.e. its `active + pending != desired` and their respective values has remained exactly same for say an hour or so. Does that make sense?

**Comment by cyli** [comment]
@manishtomar Yes, that seems like a good way of going about it.  We had previously discussed converging on a schedule anyway (like once an hour or so just schedule a convergence), and this would give us more data about whether that would help things (since if the solution is just to re-converge, automating the process would be nice).

**Comment by radix** [comment]
Is this something that could be done by Sam's new thing?

**Comment by manishtomar** [comment]
> Is this something that could be done by Sam's new thing?

@sam-falvo thing is something that reacts based on otter's logs. This email is primarily OOB checking if otter is doing its job correctly. So, I think it should not be done there.

**Comment by wirehead** [comment]
I really like the idea of:
 - Having a group that's been unstable for a while get convergence automatically triggered
 - Having a group that fails to react to being triggered send out an alert.
 - Having it documented in such a way that, once we've guaranteed correct operation, we can engage another team to actually read those alerts.

OOB checking and having it send out an email is a pretty good first step.

**Comment by radix** [comment]
I like the idea of auto-converging and stuff.

But I'd rather not do our own alerting/emailing stuff: it'd be a lot nicer if we could be pumping data into an actual monitoring system that we could configure to do notifications.

**Comment by manishtomar** [comment]
> it'd be a lot nicer if we could be pumping data into an actual monitoring system that we could configure to do notifications.

+1. Let me check how I can integrate it with cloud monitoring.

**Comment by manishtomar** [comment]
I was thinking of just logging this and @sam-falvo plugin can pick it up from logstash and send notification.

**Comment by sam-falvo** [comment]
Just to remind everyone, Conveyer's job is to couple Logstash metrics gathering to cloud monitoring agent.  Conveyer **does not** do its own alerting or even monitoring.  It's just a data massager and impedance matcher between monitoring agent and Logstash.  See https://github.com/sam-falvo/conveyer

Configuration of monitoring agent plugin has to match Logstash configuration in order to convey the data appropriately.  I haven't started work on the plugin yet because I haven't fully tested the conveyer in its final resting place yet.  I want a corpus of semi-realistic data to test the plugin against first.  (Otherwise, I'm just shooting in the dark.)  That's really the only dependency I have at the moment.

**Comment by wirehead** [comment]
So, we probably should be putting this information in the log for logstash.

But Conveyor isn't really needed in this case.

Logstash can be configured to email these events (you can even use 'throttle' to avoid spamming people with tons of email).

**Comment by manishtomar** [comment]
Closing as this info will be got from logs as discussed above. This will need https://github.com/rackerlabs/autoscaling-chef/issues/762 merged though.
