### ISSUE TITLE
Spec.py has a callable for each event type that knows how to split that type of log

### ISSUE THREAD

**Issue by cyli** [rackerlabs/otter#1653]
So for instance the execute-convergence log can split if the servers list is too long, etc.

**Comment by radix** [comment]
I started on a branch a whiiiile back that would make it so you could put callables instead of formattables as the values of the log spec dictionary, and they would be called with the event dict to produce 1 or more log message. I'm not sure if I actually produced anything valuable, I'll have to check.

**Comment by manishtomar** [comment]
This can be used to split up CF messages too and help in implementing #1583. @radix Did you manage to find your branch that contains this?

**Comment by manishtomar** [comment]
`spec.py` is observing a single log event. Is it possible for it to fan it to multiple log events? As in, no matter what it does, the event is going to the next observer in the list right?

**Comment by cyli** [comment]
man

**Comment by radix** [comment]
I found the branch, it's https://github.com/rackerlabs/otter/tree/callable-specs. super simple, it doesn't allow returning a list but that shouldn't be too hard to add.

**Comment by cyli** [comment]
@radix thanks!

**Comment by cyli** [comment]
Done
