### ISSUE TITLE
Handle all the different Nova server states, also unknown Nova states

### ISSUE THREAD

**Issue by cyli** [rackerlabs/otter#1694]
@sam-falvo Found a bug while scaling up 300 servers where convergence stopped working for a while.

This was due to at least one of the servers being in a shutoff state, which we do not currently handle in our server model.  Our server model attempts to convert the Nova server status to `otter.convergence.model.ServerState`, and there are only 5 states, so the name lookup fails.  This caused gathering to repeatedly fail until all the SHUTOFF servers were removed.

(I do actually mean `SHUTOFF`, even though it's undocumented in Nova's [list of server states](http://docs.rackspace.com/servers/api/v2/cs-devguide/content/List_Servers_Server_Statuses-d1e2078.html#server_status):

```
Traceback (most recent call last):
  ...
from_server_details_json
    server_state = ServerState.lookupByName(server_json['status'])
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/twisted/python/constants.py", line 258, in lookupByName
    raise ValueError(name)
effect._intents.FirstError: (index=0) ValueError: SHUTOFF
```
)

Since `otter.convergence.model.ServerState` reflects the Autoscale conception of various state a server can be in (Nova does not have DRAINING, for instance, and Autoscale does not care about transitional states like MIGRATING, because Autoscale can take no action), we should probably translate those other unhandled Nova states to `ACTIVE`, `BUILD`, `ERROR`, `DRAINING`, or `DELETE`.

Most of the Nova states are transitional, and we can maybe translate them to `BUILD` state (since it means the server isn't active, but it's not in error or being deleted).

However, we're not sure how to handle `SUSPENDED` and `UNKNOWN`.  @manishtomar made the great suggestion of just disowning them and replacing them, since `SUSPENDED` can be by user request.  We may want to handle undocumented Nova states this way too (for instance, the `SHUTOFF` state that @sam-falvo noticed in his test).

**Comment by radix** [comment]
so to list them:

- [ ] SUSPENDED
- [ ] UNKNOWN
- [ ] SHUTOFF

**Comment by radix** [comment]
After just briefly thinking about it, I think I agree with the idea of "disowning" them (basically ignoring them as a part of the gathering process).

I think it'd be fine to just add an `UNKNOWN` state to our ServerState model, and then map all unknown states to that. I think we should still make sure to log the actual unknown state we get so we can debug problems related to this later. We can also add these other states explicitly to the model, but it's not strictly necessary. As long as we filter out all unknown + unhandled states in gathering.

**Comment by radix** [comment]
Okay, so maybe not. `SHUTOFF` servers get billed as normal (and my memory tells me that so do `SUSPENDED` servers). So at least in the case of `SHUTOFF` it seems we should really be deleting these servers. Not sure about `SUSPENDED` given that it's a state that can be entered by the user. I know from experience it can _also_ be caused automatically by rackspace (or at least without user intervention).

**Comment by cyli** [comment]
Is there a way to recover from `SHUTOFF` state?  Or even just recover data?  If not, or if you can only get to `SHUTOFF` state from `BUILD`, then we can probably count `SHUTOFF` as a sort of `ERROR` state.

I think a user can recover from `SUSPENDED`.

**Comment by radix** [comment]
I would argue that we should treat `SUSPENDED` as "to be replaced" as well. As far as I know, this happens either when some automatic tools decide to suspend an instance (like, I once had an instance suspended because it was hacked and had some spammy outbound DNS traffic), or when a support racker suspends it.  I don't think it's possible for a user to trigger `SUSPENDED` state directly.


I think I'll also suggest that we rename the values of `ServerState` like so:

- ACTIVE -> ACTIVE
- ERROR -> TO_BE_REPLACED
- BUILD -> TEMPORARILY_UNAVAILABLE
- DELETING -> DELETING

Because it's becoming less and less a reflection of the server state and more a specification of our intent of what to do with the server.

**Comment by cyli** [comment]
> I think I'll also suggest that we rename the values of `ServerState` like so:

> - ACTIVE -> ACTIVE
> - ERROR -> TO_BE_REPLACED
> - BUILD -> TEMPORARILY_UNAVAILABLE
> - DELETING -> DELETING

> Because it's becoming less and less a reflection of the server state and more a specification of our intent of what to do with the server.

+1!

**Comment by radix** [comment]
actually I think I am being swayed over to SUSPENDED -> `TEMPORARILY_UNAVAILABLE`. From what I've gathered, SUSPENDED is only triggered *manually* by support (though I wouldn't rule out some automation eventually doing it too).

The thing is, if we delete SUSPENDED servers, then we don't give anyone a chance to do forensic analysis or data recovery on the server. If we ignore them and replace them, then we may end up causing a lot of extra billing to the customer since servers will be provisioned to replace the SUSPENDED servers, which are still being billed.

As long as SUSPENDED servers can still be manually disowned through our "delete server" API I think that leaves us in an acceptable spot.

**Comment by radix** [comment]
alright I'm not totally sure about the change of ServerState attributes. I'll think about it as I hack.
