### ISSUE TITLE
Use CLB Node Metadata to limit which nodes we clean up

### ISSUE THREAD

**Issue by radix** [rackerlabs/otter#1803]
Currently, otter deletes CLB nodes that it "doesn't know about" as a part of convergence. This is done to clean up CLB nodes in the case where the user has changed the configuration from using one Load Balancer to a different one (or just removing the load balancer association entirely). The problem with this is that if a user manually adds auto-scaled servers to a load balancer, we'll immediately delete that association.

We can avoid this by putting a little flag on CLB nodes that indicates that they are otter-managed. I think all it needs to be is a boolean, but we may want to make it point to server ID and group ID to make debugging easier. The behavior in change will be: if this flag exists, then deletion will proceed as it currently does. If the flag is *not* there, we will not delete the node. This way manually added nodes will not be deleted.

This will require:

- `cloud_client.py` function for adding node metadata
- `cloud_client.py` function for *retrieving* node metadata, since apparently it's not returned with the normal list nodes or node details calls. Which means we're more likely to hit rate limits! :-(
- step in otter.convergence.steps that invokes this function
- ILBNode and CLBNode to grow a `metadata` attribute
- `gathering.py` changes to fetch metadata and populate it in the CLBNode
- some changes to `planning.py` to
  - use this step to add metadata after it sees that the node exists
  - check for the metadata flag on the node before deleting the node

**Comment by eljrax** [comment]
Really appreciate you guys taking steps to rectify this!

I'm wondering though if it's not possible to just set the metadata on the loadbalancer itself, as opposed to on each node, and only enforce this behaviour on load balancers where this flag is set?
That would probably alleviate the rate limiting woes, and nodes on load balancers where this flag isn't set would be untouched.

One wouldn't add an autoscaled node to a load balancer Otter is already managing (since it should already be there), and you can scan the load balancers on the account and if there's no mapping between an active AS group and a load balancer which has the metadata corresponding to that group - then clean the Otter managed nodes from the LB (leaving the others untouched!) and remove the metadata from the load balancer?

If the LB is added back to the scaling group - then add the metadata flag back and repeat.


This way I can be sure that if I never associate a load balancer with an autoscale group, it will never be touched by Otter. It would still need to be considered if/when moving from Otter managed to self-managed, but at least with the proposed fix, things are slightly better.
My preference would still be toward leaving cleaning up load balancers to humans/per-customer automation. It's a pretty big step, and disassociating load balancers is not something you'd do on a whim, so chances are it's already part of a planned project where 'cleaning up' would already be a step.

Disclaimer: Not being familiar with the Otter code base or operations - I'm very open to the idea that I've oversimplified things here and that there are many reasons this is not feasible. But I thought I'd throw it out there.

**Comment by manishtomar** [comment]
@eljrax Thanks for your input. I just realized an extremely simple code change that can fix this issue without the metadata. I'll think about it some more possibly discussing with Sanjay and @glyph and update here. Meanwhile, I've some thoughts on your comment above.

> My preference would still be toward leaving cleaning up load balancers to humans/per-customer automation.

By "load balancers" if you mean CLB node then I disagree. It feels strange for autoscale to add node but not delete that same node. It should either manage a CLB/port combination completely or not. Moreover, it becomes complicate to implement that. If for some reason deleting a node hinders with your workflow then either autoscale should address that workflow or you should not provide CLB in the group and manage CLB association yourself which is what you are currently doing.

**Comment by eljrax** [comment]
@manishtomar Just to clarify, I meant removing nodes from load balancers where Otter didn't put them in the first place.
The comment you quoted was in the context of if I disassociate a load balancer from a scaling group, I would ideally not want Otter to remove all the nodes from that load balancer. But that would be the case in the proposed solution.

I absolutely agree that Otter should remove autoscaled servers from load balancers I have associated with the scaling group as you say.  

Seems like we're all on the same page, looking forward to seeing what you guys come up with!

**Comment by manishtomar** [comment]
@eljrax Please note that otter only removes nodes of a particular server. That server can be either a server being scaled down or an already deleted server (user deleted it manually). It does not touch other nodes in that CLB. I think that's a sane behavior. The extra thing that otter does is that it removes nodes of that server from _all_ CLBs which may include CLB not configured in the group. I think that is also fine since having any CLB node pointing to invalid IP address is bad especially since that IP can get recycled to another tenant. Kindly let me know if you are fine with this behavior. Meanwhile, if possible kindly join #otter in rackspace.slack.com and we can have more real time discussion there :)

**Comment by eljrax** [comment]
@manishtomar It's that extra bit where it removes it from *all* CLBs that I'm struggling with. There are use-cases where you can legitimately want to add an autoscaled node to another load balancer, even if temporary. You may also want to have more control over at what point in a scale-up scenario a node is added to the CLB (ie. wait until config management and/or integration testing/health check has finished before adding the node). 
But I believe this is what @radix aims to solve here, so it's all good!

I'll jump on #otter, cheers!

**Comment by manishtomar** [comment]
The simple change which can fix this without storing node metadata is removing https://github.com/rackerlabs/otter/blob/master/otter/convergence/planning.py#L198-L203 lines. With this the behavior is that "otter will ensure that server is added/changed in desired CLBs but will not remove it from any other CLBs".
