### ISSUE TITLE
ERROR Group should become ACTIVE at beginning of convergence

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#1809]
When user finds ERROR group with information about invalid launch config, he/she will fix the launch config and call `converge`. At that time, the group status is still shown as ERROR and is updated to ACTIVE only after convergence succeeds which can be multiple cycles resulting in a update potentially after 1-2 minutes depending on the group and number of resources created/deleted. During that time the group is technically _active_ and working to bring desired state but shows ERROR. This is incorrect and results in user assuming that `converge` didn't work. The group should move to ACTIVE at beginning of convergence cycle. This way it is accurate with its definition.

**Comment by manishtomar** [comment]
@glyph Not sure whom to ask but would like your opinion on this.

**Comment by glyph** [comment]
@manishtomar - sorry for the delay. Frankly this sounds *obviously* correct to me though (I had to read it a few times because the repeated terms made my eyes glaze over a little bit) but you're right: if the group is no longer sure that the launch configuration is invalid, then during the course of discovering its validity it should be the same as if they had just created the group and it hadn't noticed the launch config was broken yet.  Is there any reason not to do it this way?

**Comment by manishtomar** [comment]
> Is there any reason not to do it this way?

https://github.com/rackerlabs/otter/issues/885#issuecomment-101413926

**Comment by glyph** [comment]
OK that sounds like @radix is just saying there "it would be correct to do this, but doing it the correct way might involve a write to the database".  So unless there's some catastrophic performance problem… yes, go ahead and do the write to the database :).

**Comment by manishtomar** [comment]
Thanks for your feedback @glyph :smiley:
