### ISSUE TITLE
Scaling group status

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#885]
The original description is https://github.com/rackerlabs/otter/issues/885#issuecomment-98007717.  There have been discussions about this and following below tasks have been decided: 
- [x] When starting convergence cycle, set group status to ACTIVE  if it is not already active. After executing set it to ERROR if group has errored.
- [x] Provide status in API (either in manifest view or state view)

**Comment by lvh** [comment]
So, FYI, I'm reasonably sure the answer for groups is:

- `ACTIVE`: working as usual.
- `ERROR`: discarding automated input, such as from the observer. You get here because we believe a group is wedged. You get out of this by manually hitting a converge endpoint, which does not check the status before starting, but does *set* the status to `ACTIVE` if it believes it completed without user errors in the group.

... keeping in mind that data gathering, and possibly convergence as a whole, needs to be a tenant-level thing (although that's a different discussion).

**Comment by manishtomar** [comment]
> ERROR: discarding automated input, such as from the observer.

What about scheduled policy execution when group is in ERROR? I am kind of leaning towards making it ACTIVE and trying to execute again since we know group ERRORs can sometimes be transient. Say if launch config's image was getting copied when group went into ERROR and there is scheduled policy in an hour. I don't have strong opinions about it though.

**Comment by lvh** [comment]
Same deal. You start a convergence cycle, and set `ACTIVE` if it worked, and `ERROR` if it failed. You want the state transition on the exit side.

**Comment by lvh** [comment]
We probably can't reasonably answer this question without first having a real answer about converge being tenant- or group-level first.

**Comment by manishtomar** [comment]
W.r.t this I think the answer is converge being group-level since each group has different launch config and only one of them maybe invalid.

**Comment by lvh** [comment]
Convergence is either group-level or tenant-level, it can't be different things with respect to different things. Convergence being group-level entirely has the issues @cyli and I highlighted re: gathering.

**Comment by manishtomar** [comment]
gathering is more of implementation detail rather than issue. Its just more efficient to converge all the groups because of the way gathering _happens_

**Comment by lvh** [comment]
I don't think that's true. It makes a pretty big difference if you're deciding to automatically put groups into `ACTIVE` when you hit the big "converge" button, for example.

**Comment by lvh** [comment]
I also don't think it's an implementation detail, because there's not really an implementation yet. I'm saying we should decide semantics, and that's the exact opposite of an implementation detail.

To quote @wirehead, "I support whatever's easier and faster, because none of our customers really care that deeply".

**Comment by manishtomar** [comment]
> Same deal. You start a convergence cycle, and set ACTIVE if it worked, and ERROR if it failed. You want the state transition on the exit side.

We can close this ticket once #1354 and above is implemented.

**Comment by manishtomar** [comment]
# Original description:

We need to decide what states the scaling group can be in and what do they really mean. Following was @lvh input in #864 from where this issue was originated:

State machines are great. However, they're only useful if the states and transitions between them are clear. While I can extract an enumeration of the states from the PR (ACTIVE and ERROR), that doesn't say anything about what those states mean. The state transitions are similarly Delphic. Fortunately, there only appear to be two introduced by this PR, and only in one location. The supervisor side of this PR somewhat arbitrarily decides that ERROR means "I tried n launches, and all of them failed".

So far, whenever we've talked about groups being in an ERROR state, we've always clearly differentiated upstream errors from user errors. A user error, such as a broken launch config, will clearly cause all launch attempts to fail. On the other hand, all launch attempts failing does not imply user error. If I understand correctly (manual inspection because no tests), if I try to scale up by one machine and Nova randomly fails, this code will conclude the group is in an ERROR state. That doesn't sound right.

Perhaps "last round of launch attempts failed" is indeed the semantics you meant to assign to ERROR, but in that case I'd suggest:

- A reason why we need a state for that, and
- a different name, since AFAICT we've already been using it to refer to wedged groups, and,
- a state that actually means "user error".

I think the only real solution here is a clear distinction between failure modes. See also: #844 and the work I'm doing around response_pred.

**Comment by radix** [comment]
So I've done both the parts of this ticket -- but I should note before closing it that I made it reactivate the group at the *end* of convergence instead of at the beginning. This is consistent with the original description and the comments in this thread, but the checkbox in the current description says to put the group into ACTIVE at the beginning.

It can be argued that it can go at the beginning or the end.

At the beginning: the user gets a quicker response in the group state when they explicitly try to reconverge. but then if it fails again we need to put it back into ERROR. Philosophically, it can be argued that the group is active while converging.

At the end: less responsive, but less churn in the database. Philosophically, it can be argued that we don't really know if the group is active until the converge is successful.

Anyway, I went with end mostly because the DB churn thing, plus it's close to the other place we check/change group state (for DELETING, and putting into ERROR).
